// ============================================
// MRK Foods - Employee Data File
// This file is generated by the Admin Panel.
// Upload this file to GitHub to publish cards.
// Generated: (not yet published)
// ============================================
window.MRK_EMPLOYEES = [];
