export default async function handler(req, res) {
  // Only allow POST
  if (req.method !== "POST") {
    return res.status(405).json({ success: false, error: "Method not allowed" });
  }

  try {
    const { employees } = req.body;

    if (!employees || !Array.isArray(employees)) {
      return res.status(400).json({ success: false, error: "Invalid or missing employees array" });
    }

    // Read environment variables
    const owner  = process.env.GITHUB_OWNER;
    const repo   = process.env.GITHUB_REPO;
    const branch = process.env.GITHUB_BRANCH || "main";
    const token  = process.env.GITHUB_TOKEN;

    // Guard: make sure all env vars are set
    if (!owner || !repo || !token) {
      return res.status(500).json({
        success: false,
        error: `Missing environment variable(s): ${[
          !owner  && "GITHUB_OWNER",
          !repo   && "GITHUB_REPO",
          !token  && "GITHUB_TOKEN",
        ].filter(Boolean).join(", ")}`
      });
    }

    const filePath = "employees-data.js";

    const apiBase = `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`;

    const headers = {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    };

    // ── STEP 1: GET existing file to retrieve its SHA ──────────────────────────
    const getResponse = await fetch(`${apiBase}?ref=${branch}`, { headers });

    let sha = null;

    if (getResponse.status === 200) {
      const fileData = await getResponse.json();
      sha = fileData.sha;
    } else if (getResponse.status === 404) {
      // File does not exist yet – we will CREATE it (sha stays null)
      sha = null;
    } else {
      // Any other status is an unexpected error
      const errBody = await getResponse.json().catch(() => ({}));
      return res.status(500).json({
        success: false,
        error: `GitHub GET failed (${getResponse.status})`,
        details: errBody,
        debug: { owner, repo, branch, filePath },
      });
    }

    // ── STEP 2: Build new file content ─────────────────────────────────────────
    const fileContent =
      `// ============================================\n` +
      `// MRK Foods - Employee Data File\n` +
      `// Auto-generated by Admin Dashboard.\n` +
      `// DO NOT edit manually.\n` +
      `// Last published: ${new Date().toISOString()}\n` +
      `// ============================================\n\n` +
      `window.MRK_EMPLOYEES = ${JSON.stringify(employees, null, 2)};\n`;

    const base64Content = Buffer.from(fileContent).toString("base64");

    // ── STEP 3: PUT (create or update) the file ────────────────────────────────
    const putBody = {
      message: `Auto-publish employee cards [${new Date().toISOString()}]`,
      content: base64Content,
      branch: branch,
    };

    // SHA is REQUIRED when updating an existing file
    if (sha) putBody.sha = sha;

    const putResponse = await fetch(apiBase, {
      method: "PUT",
      headers,
      body: JSON.stringify(putBody),
    });

    const putData = await putResponse.json().catch(() => ({}));

    if (!putResponse.ok) {
      return res.status(500).json({
        success: false,
        error: `GitHub PUT failed (${putResponse.status})`,
        details: putData,
        debug: { owner, repo, branch, filePath, sha },
      });
    }

    return res.status(200).json({
      success: true,
      message: "employees-data.js updated successfully on GitHub",
      commit: putData?.commit?.html_url || null,
    });

  } catch (err) {
    return res.status(500).json({
      success: false,
      error: "Unexpected server error",
      details: err.message,
    });
  }
}
